<?php
declare(strict_types=1);
function action(string $a): void {
 $me=user();$uid=target();
 switch($a){
 case 'password':
  if(!password_verify(post('current'),$me['password']))fail('Bisheriges Passwort stimmt nicht.');password_rule(post('new'));if(post('new')!==post('repeat'))fail('Neue Passwörter stimmen nicht überein.');update('users',(int)$me['id'],['password'=>password_hash(post('new'),PASSWORD_DEFAULT),'must_change'=>0]);session_regenerate_id(true);audit('password','users',(int)$me['id']);break;
 case 'entry_save':
  $id=(int)post('id','0');$old=$id?one('entries','id=?',[$id]):null;if($id&&!$old)fail('Eintrag nicht gefunden.');if($old){owner((int)$old['user_id']);$uid=(int)$old['user_id'];foreach(entry_months($old['start_at'],$old['end_at']) as $m)unlocked($uid,$m);}
  $start=parse_local(post('start'),post('start_offset'));$end=parse_local(post('end'),post('end_offset'));$breaks=[];
  $bs=$_POST['break_start']??[];$be=$_POST['break_end']??[];if(!is_array($bs)||!is_array($be)||count($bs)>30)fail('Ungültige Pausen.');foreach($bs as $i=>$s){if($s===''&&($be[$i]??'')==='')continue;$breaks[]=[parse_local((string)$s,(string)($_POST['break_start_offset'][$i]??'')),parse_local((string)($be[$i]??''),(string)($_POST['break_end_offset'][$i]??''))];}
  validate_interval($uid,$start,$end,$breaks,$id);$data=['user_id'=>$uid,'start_at'=>$start,'end_at'=>$end,'breaks_json'=>json_encode($breaks),'note'=>bounded(post('note'),2000),'updated_at'=>now()];$reason=admin()&&$uid!==(int)$me['id']?require_reason():post('reason');if($old)update('entries',$id,$data);else $id=insert('entries',$data);audit('save','entries',$id,$old,$data,$reason);break;
 case 'entry_delete':
  $old=one('entries','id=?',[(int)post('id')]);if(!$old)fail('Eintrag nicht gefunden.');owner((int)$old['user_id']);foreach(entry_months($old['start_at'],$old['end_at']) as $m)unlocked((int)$old['user_id'],$m);$reason=require_reason();q('DELETE FROM '.table('entries').' WHERE id=?',[$old['id']]);audit('delete','entries',(int)$old['id'],$old,null,$reason);break;
 case 'clock_start':
  $uid=(int)$me['id'];unlocked($uid,substr(today(),0,7));if(today()<$me['employment_start']||($me['employment_end']&&today()>$me['employment_end']))fail('Außerhalb der Beschäftigung.');if(one('entries','user_id=? AND (end_at IS NULL OR end_at>?)',[$uid,gmdate('Y-m-d H:i:00')]))fail('Es läuft bereits eine Zeiterfassung oder ein vorhandener Eintrag reicht bis in diese Minute.');if(one('absences',"user_id=? AND status='approved' AND fraction=1 AND start_date<=? AND end_date>=?",[$uid,today(),today()]))fail('Heute besteht eine ganztägige Abwesenheit.');$id=insert('entries',['user_id'=>$uid,'start_at'=>gmdate('Y-m-d H:i:00'),'end_at'=>null,'breaks_json'=>'[]','note'=>'','updated_at'=>now()]);audit('start','entries',$id);break;
 case 'clock_pause':case 'clock_resume':case 'clock_stop':
  $e=one('entries','user_id=? AND end_at IS NULL',[(int)$me['id']]);if(!$e)fail('Keine laufende Zeiterfassung.');foreach(entry_months($e['start_at'],now()) as $m)unlocked((int)$me['id'],$m);$p=json_decode($e['breaks_json'],true);$paused=$p&&end($p)[1]===null;$t=gmdate('Y-m-d H:i:00');
  if($a==='clock_pause'){if($paused)fail('Pause läuft bereits.');$p[]=[$t,null];}elseif($a==='clock_resume'){if(!$paused)fail('Keine laufende Pause.');if(end($p)[0]===$t)array_pop($p);else $p[count($p)-1][1]=$t;}else{if($paused){if(end($p)[0]===$t)array_pop($p);else $p[count($p)-1][1]=$t;}validate_interval((int)$me['id'],$e['start_at'],$t,$p,(int)$e['id']);}
  $d=['breaks_json'=>json_encode($p),'updated_at'=>now()];if($a==='clock_stop')$d['end_at']=$t;update('entries',(int)$e['id'],$d);audit($a,'entries',(int)$e['id'],$e,$d);break;
 case 'absence_save':
  $start=date_ok(post('start_date'));$end=date_ok(post('end_date'));if($start>$end)fail('Enddatum liegt vor dem Startdatum.');$dates=days($start,$end);$type=post('type');if(!in_array($type,['vacation','sick','comp','other'],true))fail('Ungültige Abwesenheit.');$hourly=post('fraction')==='hours';$fraction=$hourly?0.0:(float)post('fraction');$amount=$hourly?(int)round((float)post('absence_hours','0')*60):0;if((!$hourly&&!in_array($fraction,[0.5,1.0],true))||($hourly&&($amount<1||$amount>1440)))fail('Gültigen Umfang auswählen.');$person=one('users','id=?',[$uid]);if($start<$person['employment_start']||($person['employment_end']&&$end>$person['employment_end']))fail('Abwesenheit liegt außerhalb der Beschäftigung.');
  foreach($dates as $d){unlocked($uid,substr($d,0,7));if($hourly&&$amount>scheduled($uid,$d))fail('Stundenweise Abwesenheit darf die Sollzeit eines Tages nicht übersteigen.');}if(one('absences',"user_id=? AND status IN ('pending','approved') AND start_date<=? AND end_date>=?",[$uid,$end,$start]))fail('Es besteht bereits eine Abwesenheit in diesem Zeitraum.');
  absence_conflict($uid,$start,$end,$fraction);$status=$type==='sick'?'approved':'pending';$data=['user_id'=>$uid,'start_date'=>$start,'end_date'=>$end,'type'=>$type,'fraction'=>$fraction,'amount_minutes'=>$amount,'status'=>$status,'note'=>bounded(post('note'),2000),'response'=>'','created_at'=>now()];$id=insert('absences',$data);audit('create','absences',$id,null,$data);notify_admins($person['name'].': neue Abwesenheit eingereicht.');break;
 case 'absence_review':
  require_admin();$old=one('absences','id=?',[(int)post('id')]);if(!$old)fail('Abwesenheit nicht gefunden.');if($old['status']!=='pending')fail('Nur offene Anträge können entschieden werden.');$status=post('status');if(!in_array($status,['approved','rejected'],true))fail('Ungültiger Status.');foreach(days($old['start_date'],$old['end_date']) as $d)unlocked((int)$old['user_id'],substr($d,0,7));if($status==='approved')absence_conflict((int)$old['user_id'],$old['start_date'],$old['end_date'],(float)$old['fraction']);$r=bounded(post('reason'),1000);update('absences',(int)$old['id'],['status'=>$status,'response'=>$r]);audit('review','absences',(int)$old['id'],$old,['status'=>$status],$r);notify((int)$old['user_id'],'Ihre Abwesenheit wurde bearbeitet: '.($status==='approved'?'freigegeben':'abgelehnt').'.');break;
 case 'absence_cancel':
  $old=one('absences','id=?',[(int)post('id')]);if(!$old)fail('Abwesenheit nicht gefunden.');owner((int)$old['user_id']);if($old['status']==='cancelled')fail('Dieser Antrag ist bereits zurückgezogen.');if(!admin()&&!in_array($old['status'],['pending','rejected'],true))fail('Nur offene oder abgelehnte Anträge können selbst zurückgezogen werden.');if($old['status']!=='rejected')foreach(days($old['start_date'],$old['end_date']) as $d)unlocked((int)$old['user_id'],substr($d,0,7));$r=require_reason();update('absences',(int)$old['id'],['status'=>'cancelled','response'=>$r]);audit('cancel','absences',(int)$old['id'],$old,['status'=>'cancelled'],$r);break;
 case 'close_month':
  $month=month_ok(post('month'));$old=one('closures','user_id=? AND month=?',[$uid,$month]);$status=post('status');$comment=bounded(post('reason'),1000);if($status==='submitted'){if($month>=substr(today(),0,7))fail('Nur abgeschlossene Monate einreichen.');unlocked($uid,$month);foreach(rows('entries','user_id=? AND end_at IS NULL',[$uid]) as $e)if(in_array($month,entry_months($e['start_at'],now()),true))fail('Bitte laufende Zeiterfassung zuerst beenden.');if(one('absences',"user_id=? AND status='pending' AND start_date<=? AND end_date>=?",[$uid,(new DateTimeImmutable($month.'-01'))->format('Y-m-t'),$month.'-01']))fail('Bitte offene Abwesenheitsanträge zuerst klären.');}
  elseif(in_array($status,['approved','returned','open'],true)){require_admin();if(!$old)fail('Der Monat wurde noch nicht eingereicht.');if($status==='approved'&&$old['status']!=='submitted')fail('Nur eingereichte Monate können freigegeben werden.');$comment=require_reason();}else fail('Ungültiger Status.');
  $data=['user_id'=>$uid,'month'=>$month,'status'=>$status,'comment'=>$comment,'updated_at'=>now(),'snapshot'=>$status==='approved'?json_encode(month_report($uid,$month,false),JSON_UNESCAPED_UNICODE):null];$id=$old?(int)$old['id']:insert('closures',$data);if($old)update('closures',$id,$data);audit('status','closures',$id,$old,$data,$comment);if($status==='submitted')notify_admins('Ein Monatszettel '.$month.' wurde eingereicht.');else notify($uid,'Ihr Monatszettel '.$month.' wurde bearbeitet.');break;
 case 'document_upload':
  $f=upload_file('file',['application/pdf'=>'pdf','image/jpeg'=>'jpg','image/png'=>'png']);$aid=(int)post('absence_id','0');if($aid&&!one('absences','id=? AND user_id=?',[$aid,$uid]))fail('Abwesenheit gehört nicht zu diesem Mitarbeiter.');$name=bin2hex(random_bytes(24)).'.'.$f['ext'];if(!move_uploaded_file($f['tmp_name'],storage_path($name)))fail('Datei konnte nicht gespeichert werden.');$id=insert('documents',['user_id'=>$uid,'title'=>bounded(post('title'),190),'category'=>bounded(post('category'),80),'absence_id'=>$aid?:null,'original_name'=>bounded(basename($f['name']),190),'storage_name'=>$name,'mime'=>$f['mime'],'size'=>$f['size'],'status'=>'submitted','note'=>bounded(post('note'),2000),'response'=>'','created_at'=>now()]);audit('upload','documents',$id);notify_admins('Ein neues Dokument wurde eingereicht.');break;
 case 'document_review':
  require_admin();$d=one('documents','id=?',[(int)post('id')]);if(!$d)fail('Dokument nicht gefunden.');$s=post('status');if(!in_array($s,['processing','done','rejected'],true))fail('Ungültiger Status.');$r=bounded(post('response'),2000);update('documents',(int)$d['id'],['status'=>$s,'response'=>$r]);audit('review','documents',(int)$d['id'],['status'=>$d['status']],['status'=>$s]);notify((int)$d['user_id'],'Ihr eingereichtes Dokument wurde bearbeitet.');break;
 case 'document_delete':
  $d=one('documents','id=?',[(int)post('id')]);if(!$d)fail('Dokument nicht gefunden.');owner((int)$d['user_id']);if(!admin()&&$d['status']!=='submitted')fail('Bereits bearbeitete Dokumente kann nur ein Administrator löschen.');$r=require_reason();q('DELETE FROM '.table('documents').' WHERE id=?',[$d['id']]);audit('delete','documents',(int)$d['id'],['id'=>$d['id'],'user_id'=>$d['user_id']],null,$r);$GLOBALS['delete_after_commit'][]=storage_path($d['storage_name']);break;
 case 'notifications_read':q('UPDATE '.table('notifications').' SET seen=1 WHERE user_id=?',[$me['id']]);break;
 default: admin_action($a,$uid);
 }
}
function absence_conflict(int $uid,string $start,string $end,float $fraction): void {if($fraction<1)return;$a=(new DateTimeImmutable($start,tz()))->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');$b=(new DateTimeImmutable($end,tz()))->modify('+1 day')->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');if(one('entries','user_id=? AND start_at<? AND (end_at IS NULL OR end_at>?)',[$uid,$b,$a]))fail('Ganztägige Abwesenheit überschneidet sich mit Arbeitszeit.');}
function upload_file(string $field,array $allowed): array {
 $f=$_FILES[$field]??null;if(!$f||$f['error']!==UPLOAD_ERR_OK)fail('Upload fehlgeschlagen. Dateigröße und Hostinglimit prüfen.');$max=(int)setting('upload_mb','10')*1048576;if($f['size']>$max)fail('Datei ist größer als das erlaubte Uploadlimit.');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);if(!isset($allowed[$mime]))fail('Dateiformat ist nicht erlaubt.');if(str_starts_with($mime,'image/')&&!getimagesize($f['tmp_name']))fail('Ungültige Bilddatei.');if($mime==='application/pdf'&&file_get_contents($f['tmp_name'],false,null,0,5)!=='%PDF-')fail('Ungültige PDF-Datei.');return $f+['mime'=>$mime,'ext'=>$allowed[$mime]];
}
