<?php
declare(strict_types=1);
function form_start(string $action,array $hidden=[],bool $file=false): void { echo '<form method="post"'.($file?' enctype="multipart/form-data"':'').'>'.csrf_field().'<input type="hidden" name="action" value="'.h($action).'">';foreach($hidden as $k=>$v)echo '<input type="hidden" name="'.h($k).'" value="'.h($v).'">'; }
function field(string $label,string $name,mixed $value='',string $type='text',string $extra=''): void { echo '<label>'.h($label).'<input type="'.h($type).'" name="'.h($name).'" value="'.h($value).'" '.$extra.'></label>'; }
function textarea(string $label,string $name,string $value='',bool $required=false): void { echo '<label>'.h($label).'<textarea name="'.h($name).'" rows="2" '.($required?'required':'').'>'.h($value).'</textarea></label>'; }
function select_field(string $label,string $name,array $options,mixed $value=''): void {echo '<label>'.h($label).'<select name="'.h($name).'">';foreach($options as $k=>$v)echo '<option value="'.h($k).'"'.((string)$value===(string)$k?' selected':'').'>'.h($v).'</option>';echo '</select></label>';}
function submit(string $label='Speichern',string $class=''): void {echo '<button class="'.h($class).'">'.h($label).'</button></form>';}
function logo(string $kind='company_logo'): string {return setting($kind)!==''?'<img class="'.($kind==='company_logo'?'company-logo':'developer-logo').'" src="index.php?asset='.h($kind).'" alt="'.h($kind==='company_logo'?setting('company'): 'IT-Janz').'">':'';}
function layout_start(string $title): void {
 $u=user();$page=$_GET['page']??'dashboard';$links=['dashboard'=>['Übersicht','▦'],'times'=>['Arbeitszeiten','◷'],'absences'=>['Abwesenheiten','▤'],'reports'=>['Monatsberichte','▥'],'documents'=>['Dokumente','▧']];
 ?><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#117a82"><title><?=h($title)?> · MaStunden</title><link rel="stylesheet" href="assets/app.css?v=<?=h(APP_VERSION)?>"><link rel="stylesheet" href="index.php?theme=1"><script src="assets/app.js?v=<?=h(APP_VERSION)?>" defer></script></head><body><?php if($u):?><aside class="sidebar" id="main-menu"><a class="app-brand" href="index.php"><span class="brand-mark small">Ma<span>St</span></span><span>MaStunden</span></a><?=logo()?><p class="nav-label">ARBEITSPLATZ</p><nav><?php foreach($links as $key=>[$label,$icon])echo '<a class="'.($page===$key?'active':'').'" href="index.php?page='.$key.'"><span>'.$icon.'</span>'.$label.'</a>';if(admin()){echo '<p class="nav-label">VERWALTUNG</p>';foreach(['team'=>'Mitarbeiter','approvals'=>'Freigaben','settings'=>'Unternehmen','backup'=>'Backup & Wiederherstellung','audit'=>'Änderungsprotokoll'] as $key=>$label)echo '<a class="'.($page===$key?'active':'').'" href="index.php?page='.$key.'">'.h($label).'</a>';}?></nav><div class="developer"><span class="developer-credit"><span>Entwickelt von</span><img src="assets/it-janz-logo.png" alt="IT-Janz" width="300" height="107"></span></div></aside><div class="workspace"><header class="topbar"><button class="mobile-toggle secondary" type="button" aria-label="Menü öffnen" aria-controls="main-menu" aria-expanded="false">☰</button><span class="breadcrumb">Ihr Arbeitsalltag. Gut im Blick.</span><a href="index.php?page=account" class="user-chip"><span class="avatar"><?=h(mb_substr($u['name'],0,1))?></span><span><?=h($u['name'])?><small><?=admin()?'Administrator':'Mitarbeiter'?></small></span></a><?php form_start('logout');submit('Abmelden','text-button');?></header><main class="content"><div class="page-heading"><div><p class="eyebrow"><?=h(setting('company',''))?></p><h1><?=h($title)?></h1></div><span class="today"><?=h((new DateTimeImmutable('now',tz()))->format('d.m.Y'))?></span></div><?php else: ?><main class="login-wrap"><section class="login-intro"><div class="app-brand"><span class="brand-mark">Ma<span>St</span></span><span>MaStunden</span></div><div><p class="eyebrow">ZEIT FÜR DAS WESENTLICHE</p><h1>Ein guter Arbeitstag<br>beginnt mit Überblick.</h1><p>Arbeitszeiten, Abwesenheiten und Unterlagen.<br>Alles an einem Ort.</p></div><p class="developer"><span class="developer-credit"><span>Entwickelt von</span><img src="assets/it-janz-logo.png" alt="IT-Janz" width="300" height="107"></span></p></section><section class="login-card"><?=logo()?><p class="eyebrow"><?=h(setting('company',''))?></p><h2><?=h($title)?></h2><?php endif;
 if(isset($_SESSION['flash'])){echo '<div class="alert">'.h($_SESSION['flash']).'</div>';unset($_SESSION['flash']);}if(!empty($GLOBALS['error']))echo '<div class="alert error" role="alert">'.h($GLOBALS['error']).'</div>';
}
function layout_end(): void { if(user()){echo '</main></div>'; }else{echo '<div class="legal-links">';foreach(['imprint'=>'Impressum','privacy'=>'Datenschutz'] as $k=>$v)if(setting($k)!=='')echo '<a href="'.h(setting($k)).'">'.$v.'</a>';echo '</div></section></main>';}echo '</body></html>'; }
function filter_bar(int $uid,string $month,string $page,bool $monthInput=true): void {echo '<form method="get" class="filters"><input type="hidden" name="page" value="'.h($page).'">';if(admin()){ $opts=[];foreach(rows('users','1',[],'ORDER BY active DESC,name') as $u)$opts[$u['id']]=$u['name'].($u['active']?'':' (inaktiv)');select_field('Mitarbeiter','user',$opts,$uid);}if($monthInput)field('Monat','month',$month,'month');echo '<button class="secondary">Anzeigen</button></form>';}
function empty_state(string $title,string $text): void { echo '<div class="empty"><span>✓</span><h3>'.h($title).'</h3><p>'.h($text).'</p></div>'; }
function offset_field(string $name,string $value=''): void {select_field('UTC-Abstand (nur Zeitumstellung)',$name,[''=>'Automatisch','+01:00'=>'+01:00 · Winterzeit','+02:00'=>'+02:00 · Sommerzeit'],$value);}
function render_page(string $page): void {
 switch($page){case 'dashboard':view_dashboard();break;case 'times':view_times();break;case 'absences':view_absences();break;case 'reports':view_reports();break;case 'documents':view_documents();break;case 'account':view_account();break;case 'welcome':view_welcome();break;default:render_admin_page($page);}
}
function view_dashboard(): void {
 $uid=(int)user()['id'];$month=substr(today(),0,7);$r=month_report($uid,$month);$vac=vacation($uid,(int)substr(today(),0,4));$worked=array_sum(array_column(array_filter($r['days'],fn($d)=>$d['day']<=today()),'work'));$current=one('entries','user_id=? AND end_at IS NULL',[$uid]);$p=$current?json_decode($current['breaks_json'],true):[];$paused=$p&&end($p)[1]===null;
 echo '<p class="lead">Hallo '.h(explode(' ',user()['name'])[0]).', hier ist Ihr Überblick.</p><div class="stats">';foreach([['Arbeitszeit im Monat',hours($worked),'Stunden erfasst'],['Stundenkonto',hours(balance($uid,today())),'Saldo bis heute'],['Resturlaub',(string)$vac['remaining'],'Tage · '.$vac['pending'].' beantragt']] as [$label,$value,$hint])echo '<section class="stat"><p>'.h($label).'</p><strong>'.h($value).'</strong><small>'.h($hint).'</small></section>';echo '</div><div class="two-columns"><section class="card timer-card"><div class="section-heading"><h2>Ihr Arbeitstag</h2><span class="badge '.($current?'approved':'open').'">'.($current?($paused?'Pause':'Erfassung läuft'):'Bereit').'</span></div><div class="clock">'.h($current?local_time($current['start_at'],'H:i'):'--:--').'</div><p class="muted">'.($current?'Arbeitsbeginn · '.h(local_time($current['start_at'],'d.m.Y')):'Starten Sie Ihre Arbeitszeit mit einem Klick.').'</p><div class="button-row">';if(!$current){form_start('clock_start');submit('▶ Arbeit starten');}else{form_start($paused?'clock_resume':'clock_pause');submit($paused?'Weiterarbeiten':'Pause starten','secondary');form_start('clock_stop');submit('■ Arbeit beenden');}echo '</div><a class="subtle-link" href="index.php?page=times">Zeiten nachtragen oder korrigieren →</a></section><section class="card"><h2>Noch zu erledigen</h2>';
 $warnings=array_values(array_filter($r['days'],fn($d)=>$d['warnings']));if(!$warnings)empty_state('Alles im Blick','Für diesen Monat gibt es keine offenen Hinweise.');else{echo '<ul class="task-list">';foreach(array_slice($warnings,0,6) as $d)echo '<li><a href="index.php?page=times&month='.$month.'">'.h((new DateTimeImmutable($d['day']))->format('d.m.')).' · '.h(implode(', ',$d['warnings'])).'</a></li>';echo '</ul>';}echo '</section></div>';
 if(admin()){ $counts=[['Offene Abwesenheiten',count(rows('absences',"status='pending'")),'approvals'],['Monate zur Freigabe',count(rows('closures',"status='submitted'")),'approvals'],['Neue Dokumente',count(rows('documents',"status='submitted'")),'documents&all=1']];echo '<div class="stats compact">';foreach($counts as [$label,$n,$link])echo '<a class="stat" href="index.php?page='.$link.'"><p>'.h($label).'</p><strong>'.$n.'</strong></a>';echo '</div>';}
 $showRead=($_GET['show_read']??'')==='1';$notePage=max(1,min(100000,(int)($_GET['notes_page']??1)));$where='user_id=?'.($showRead?'':' AND seen=0');$notes=rows('notifications',$where,[$uid],'ORDER BY id DESC LIMIT 21 OFFSET '.(($notePage-1)*20));$more=count($notes)>20;$notes=array_slice($notes,0,20);
 echo '<section class="card" id="notifications"><div class="section-heading"><h2>Mitteilungen</h2><div class="notification-controls"><a class="button secondary" href="index.php?page=dashboard'.($showRead?'':'&amp;show_read=1').'#notifications" aria-controls="notification-list" aria-expanded="'.($showRead?'true':'false').'">'.($showRead?'Gelesene ausblenden':'Gelesene anzeigen').'</a>';form_start('notifications_read');submit('Als gelesen markieren','text-button');echo '</div></div><div id="notification-list">';if(!$notes)echo '<p class="muted">'.($showRead?'Keine Mitteilungen vorhanden.':'Keine ungelesenen Mitteilungen.').'</p>';foreach($notes as $n)echo '<div class="notice '.(!$n['seen']?'unread':'').'">'.h($n['message']).'<small>'.h(local_time($n['created_at'])).' · '.($n['seen']?'Gelesen':'Ungelesen').'</small></div>';echo '</div><div class="button-row">';$noteBase='index.php?page=dashboard'.($showRead?'&amp;show_read=1':'');if($notePage>1)echo '<a class="button secondary" href="'.$noteBase.'&amp;notes_page='.($notePage-1).'#notifications">Neuere Mitteilungen</a>';if($more)echo '<a class="button secondary" href="'.$noteBase.'&amp;notes_page='.($notePage+1).'#notifications">Ältere Mitteilungen</a>';echo '</div></section>';
}
function view_times(): void {
 $uid=target();$month=month_ok((string)($_GET['month']??substr(today(),0,7)));filter_bar($uid,$month,'times');$r=month_report($uid,$month);$closure=one('closures','user_id=? AND month=?',[$uid,$month]);if($closure)echo '<div class="alert">Monatsstatus: '.badge($closure['status']).' '.h($closure['comment']).'</div>';
 $edit=isset($_GET['edit'])?one('entries','id=?',[(int)$_GET['edit']]):null;if($edit){owner((int)$edit['user_id']);$uid=(int)$edit['user_id'];}
 echo '<details class="card editor"'.($edit?' open':'').'><summary>'.($edit?'Arbeitszeit bearbeiten':'+ Arbeitszeit nachtragen').'</summary>';form_start('entry_save',['user_id'=>$uid,'id'=>$edit['id']??0]);echo '<div class="form-grid">';field('Beginn','start',$edit?local_time($edit['start_at'],'Y-m-d\TH:i'):today().'T08:00','datetime-local','required');field('Ende','end',$edit?local_time($edit['end_at'],'Y-m-d\TH:i'):today().'T16:30','datetime-local','required');echo '</div><details class="advanced"><summary>Zeitumstellung: UTC-Abstand festlegen</summary><div class="form-grid">';offset_field('start_offset',$edit?local_time($edit['start_at'],'P'):'');offset_field('end_offset',$edit&&$edit['end_at']?local_time($edit['end_at'],'P'):'');echo '</div></details><h3>Pausen</h3><div id="breaks">';$breaks=$edit?json_decode($edit['breaks_json'],true):[];if(!$breaks)$breaks=[['','']];foreach($breaks as $p)render_break($p);echo '</div><button type="button" class="secondary" id="add-break">+ Weitere Pause</button>';textarea('Bemerkung','note',$edit['note']??'');textarea('Begründung (bei Admin-Korrekturen erforderlich)','reason');submit('Arbeitszeit speichern');echo '</details><section class="card"><div class="section-heading"><h2>Monatsübersicht</h2><strong>'.hours($r['sum']['work']).' Std.</strong></div><div class="table-wrap"><table><thead><tr><th>Tag</th><th>Arbeitsblöcke</th><th>Pause</th><th>Ist</th><th>Soll</th><th>Hinweise</th></tr></thead><tbody>';foreach($r['days'] as $d)echo '<tr class="'.($d['day']===today()?'highlight':'').'"><td>'.h((new DateTimeImmutable($d['day']))->format('d.m.')).'</td><td>'.h(implode(', ',$d['blocks'])?:'—').'</td><td>'.hours($d['break']).'</td><td><strong>'.hours($d['work']).'</strong></td><td>'.hours($d['target']).'</td><td>'.h($d['label']).($d['warnings']?'<small class="warning">'.h(implode(' · ',$d['warnings'])).'</small>':'').'</td></tr>';echo '</tbody></table></div></section>';
 $from=(new DateTimeImmutable($month.'-01',tz()))->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');$to=(new DateTimeImmutable($month.'-01',tz()))->modify('+1 month')->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');$entries=rows('entries','user_id=? AND start_at<? AND (end_at IS NULL OR end_at>?)',[$uid,$to,$from],'ORDER BY start_at DESC');echo '<section class="card"><h2>Einträge bearbeiten</h2>';if(!$entries)empty_state('Noch keine Arbeitszeiten','Tragen Sie einen Arbeitsblock ein oder starten Sie die Zeiterfassung.');foreach($entries as $e){echo '<div class="entry-row"><div><strong>'.h(local_time($e['start_at'])).' – '.h(local_time($e['end_at'])).'</strong><p>'.h($e['note']).'</p></div><a class="button secondary" href="index.php?page=times&user='.$uid.'&month='.$month.'&edit='.$e['id'].'">Bearbeiten</a><details><summary>Löschen</summary>';form_start('entry_delete',['id'=>$e['id']]);field('Begründung','reason','','text','required');submit('Eintrag löschen','danger');echo '</details></div>';}echo '</section>';
}
function render_break(array $p): void {echo '<div class="break-row"><div class="form-grid">';field('Pausenbeginn','break_start[]',$p[0]?local_time($p[0],'Y-m-d\TH:i'):'','datetime-local');field('Pausenende','break_end[]',$p[1]?local_time($p[1],'Y-m-d\TH:i'):'','datetime-local');echo '</div><details class="advanced"><summary>UTC-Abstand der Pause</summary><div class="form-grid">';offset_field('break_start_offset[]',$p[0]?local_time($p[0],'P'):'');offset_field('break_end_offset[]',$p[1]?local_time($p[1],'P'):'');echo '</div></details><button type="button" class="text-button remove-break">Pause entfernen</button></div>';}
function view_absences(): void {
 $uid=target();$month=month_ok((string)($_GET['month']??substr(today(),0,7)));filter_bar($uid,$month,'absences');$v=vacation($uid,(int)substr($month,0,4));echo '<div class="stats">';foreach(['entitlement'=>'Anspruch inkl. Korrekturen','used'=>'Genehmigt','remaining'=>'Resturlaub'] as $k=>$label)echo '<div class="stat"><p>'.h($label).'</p><strong>'.$v[$k].'</strong><small>Tage im Jahr '.h(substr($month,0,4)).'</small></div>';echo '</div><details class="card editor"><summary>+ Abwesenheit melden oder beantragen</summary>';form_start('absence_save',['user_id'=>$uid]);echo '<div class="form-grid">';select_field('Art','type',['vacation'=>'Urlaub beantragen','sick'=>'Krankheit melden','comp'=>'Freizeitausgleich beantragen','other'=>setting('other_absence_label','Sonstige Abwesenheit')]);select_field('Umfang pro Tag','fraction',['1'=>'Ganzer Tag','0.5'=>'Halber Tag','hours'=>'Stundenweise']);field('Stunden pro Tag (nur stundenweise)','absence_hours','1','number','min="0.25" max="24" step="0.25"');field('Von','start_date',today(),'date','required');field('Bis','end_date',today(),'date','required');echo '</div>';textarea('Bemerkung (keine Diagnose erforderlich)','note');submit('Einreichen');echo '</details><section class="card"><h2>Abwesenheiten</h2>';$list=rows('absences','user_id=? AND start_date<=? AND end_date>=?',[$uid,(new DateTimeImmutable($month.'-01'))->format('Y-m-t'),$month.'-01'],'ORDER BY start_date DESC');if(!$list)empty_state('Keine Abwesenheiten','Für diesen Monat sind keine Abwesenheiten eingetragen.');foreach($list as $a){echo '<article class="entry-row"><div>'.badge($a['type']).' '.badge($a['status']).'<h3>'.h($a['start_date']).' bis '.h($a['end_date']).' · '.((int)($a['amount_minutes']??0)>0?hours((int)$a['amount_minutes']).' Std. pro Tag':($a['fraction']==0.5?'halbtags':'ganztags')).'</h3><p>'.h($a['note']).'</p><small>'.h($a['response']).'</small></div>';if($a['status']!=='cancelled'&&(in_array($a['status'],['pending','rejected'],true)||admin())){echo '<details><summary>Zurückziehen / stornieren</summary>';form_start('absence_cancel',['id'=>$a['id']]);field('Begründung','reason','','text','required');submit('Stornieren','danger');echo '</details>';}echo '</article>';}echo '</section>';
}
function view_documents(): void {
 $uid=target();filter_bar($uid,substr(today(),0,7),'documents',false);if(admin())echo '<p><a href="index.php?page=documents&all=1">Dokumente aller Mitarbeiter anzeigen</a></p>';echo '<details class="card editor"><summary>+ Unterlagen einreichen</summary>';form_start('document_upload',['user_id'=>$uid],true);echo '<div class="form-grid">';field('Titel','title','','text','required maxlength="190"');select_field('Kategorie','category',['Allgemein'=>'Allgemein','Abwesenheit'=>'Nachweis zur Abwesenheit','Personal'=>'Personalunterlagen','Sonstiges'=>'Sonstiges']);$opts=['0'=>'Kein Bezug'];foreach(rows('absences','user_id=?',[$uid],'ORDER BY start_date DESC LIMIT 100') as $a)$opts[$a['id']]=$a['start_date'].' – '.$a['end_date'].' · '.$a['type'];select_field('Bezug zu einer Abwesenheit','absence_id',$opts);field('PDF, JPG oder PNG · maximal '.setting('upload_mb','10').' MB','file','','file','required accept="application/pdf,image/jpeg,image/png"');echo '</div>';textarea('Kommentar','note');submit('Geschützt hochladen');echo '</details><section class="card"><h2>Eingereichte Unterlagen</h2>';$list=admin()&&isset($_GET['all'])?rows('documents','1',[],'ORDER BY id DESC LIMIT 200'):rows('documents','user_id=?',[$uid],'ORDER BY id DESC LIMIT 200');if(!$list)empty_state('Noch keine Unterlagen','Ihre hochgeladenen Dokumente und Rückmeldungen erscheinen hier.');foreach($list as $d){echo '<article class="document-row"><div><h3>'.h($d['title']).'</h3><p>'.h(one('users','id=?',[$d['user_id']])['name']).' · '.h($d['category']).' · '.h(local_time($d['created_at'])).' · '.round($d['size']/1024).' KB</p>'.badge($d['status']).'<p>'.h($d['note']).'</p><p>'.h($d['response']).'</p><a href="index.php?download='.$d['id'].'" class="button secondary">Herunterladen</a></div><div>';if(admin()){form_start('document_review',['id'=>$d['id']]);select_field('Bearbeitung','status',['processing'=>'In Prüfung','done'=>'Bearbeitet','rejected'=>'Zurückgewiesen'],$d['status']);textarea('Rückmeldung','response',$d['response']);submit('Status speichern','secondary');}if(admin()||$d['status']==='submitted'){echo '<details><summary>Dokument löschen</summary>';form_start('document_delete',['id'=>$d['id']]);field('Begründung','reason','','text','required');submit('Unwiderruflich löschen','danger');echo '</details>';}echo '</div></article>';}echo '</section>';
}
function view_account(): void {echo '<section class="card narrow"><h2>Passwort ändern</h2><p class="muted">Verwenden Sie mindestens 12 Zeichen. Nach einer Zurücksetzung muss das vorläufige Passwort geändert werden.</p>';form_start('password');field('Bisheriges Passwort','current','','password','required autocomplete="current-password"');echo '<div class="form-grid password-pair">';field('Neues Passwort','new','','password','required minlength="12" maxlength="72" autocomplete="new-password"');field('Neues Passwort wiederholen','repeat','','password','required');echo '</div>';submit('Passwort ändern');echo '</section>';}
function view_welcome(): void {echo '<section class="card narrow"><h2>MaStunden ist eingerichtet.</h2><p>Bewahren Sie den Wiederherstellungsschlüssel getrennt von Ihrem Passwort sicher auf. Er wird nur einmal angezeigt und ermöglicht die Wiederherstellung des Administratorzugangs.</p>';if(isset($_SESSION['recovery_once'])){echo '<code class="recovery">'.h($_SESSION['recovery_once']).'</code>';unset($_SESSION['recovery_once']);}echo '<ol><li>Unternehmensangaben und Logos ergänzen.</li><li>Feiertage und Arbeitszeitregeln prüfen.</li><li>Mitarbeiter anlegen und Arbeitszeitmodelle hinterlegen.</li><li>Ein erstes Backup erstellen.</li></ol><a class="button" href="index.php?page=settings">Unternehmen einrichten</a></section>';}
