<?php
declare(strict_types=1);
function view_reports(): void {
 $uid=target();$month=month_ok((string)($_GET['month']??substr(today(),0,7)));filter_bar($uid,$month,'reports');$r=month_report($uid,$month);$c=one('closures','user_id=? AND month=?',[$uid,$month]);echo '<section class="card"><div class="section-heading"><h2>Monatszettel · '.h($r['user']['name']).'</h2>'.badge($c['status']??'open').'</div><div class="button-row"><a class="button secondary" href="index.php?export=pdf&user='.$uid.'&month='.$month.'">PDF herunterladen</a><a class="button secondary" href="index.php?export=csv&user='.$uid.'&month='.$month.'">CSV exportieren</a><a class="button secondary" target="_blank" href="index.php?export=print&user='.$uid.'&month='.$month.'">Druckansicht</a></div>';report_table($r);echo '<p class="muted">'.h($c['comment']??'').'</p>';
 if(!in_array($c['status']??'open',['submitted','approved'],true)){form_start('close_month',['user_id'=>$uid,'month'=>$month,'status'=>'submitted']);submit('Monat zur Prüfung einreichen');}
 if(admin()&&$c){form_start('close_month',['user_id'=>$uid,'month'=>$month]);$opts=$c['status']==='submitted'?['approved'=>'Freigeben','returned'=>'Zur Korrektur zurückgeben']:['open'=>'Mit Begründung wieder öffnen'];select_field('Monatsabschluss','status',$opts);textarea('Begründung / Rückmeldung','reason','',true);submit('Status ändern');}echo '</section>';
 if(admin()){echo '<section class="card"><h2>Teambericht · '.h($month).'</h2><p class="muted">Einzelne oder alle Mitarbeiter auswählen. PDF enthält einen Monatszettel pro Person; CSV enthält die Tagesdaten aller ausgewählten Personen.</p><form method="get"><input type="hidden" name="month" value="'.$month.'"><div class="team-selection">';foreach(rows('users','employment_start<=? AND (employment_end IS NULL OR employment_end>=?)',[(new DateTimeImmutable($month.'-01'))->format('Y-m-t'),$month.'-01'],'ORDER BY name') as $u)echo '<label class="checkbox"><input type="checkbox" name="users[]" value="'.$u['id'].'" checked>'.h($u['name']).'</label>';echo '</div><div class="button-row"><button name="export" value="pdf">Gesammelte Monatszettel (PDF)</button><button class="secondary" name="export" value="csv">Teamdaten (CSV)</button><button class="secondary" name="export" value="summary">Gesamtbericht (PDF)</button></div></form></section>';}
}
function report_table(array $r): void {
 echo '<div class="table-wrap"><table><thead><tr><th>Datum</th><th>Arbeitsblöcke</th><th>Pause</th><th>Ist</th><th>Soll</th><th>Gutschrift</th><th>Saldo</th><th>Abwesenheit</th></tr></thead><tbody>';foreach($r['days'] as $d)echo '<tr><td>'.h((new DateTimeImmutable($d['day']))->format('d.m.Y')).'</td><td>'.h(implode(', ',$d['blocks'])).'</td><td>'.hours($d['break']).'</td><td>'.hours($d['work']).'</td><td>'.hours($d['target']).'</td><td>'.hours($d['credit']).'</td><td>'.hours($d['balance']).'</td><td>'.h($d['label']).'</td></tr>';echo '</tbody><tfoot><tr><th colspan="2">Summe</th>';foreach(['break','work','target','credit','balance'] as $k)echo '<th>'.hours($r['sum'][$k]).'</th>';echo '<th></th></tr></tfoot></table></div><p class="muted">Saldo einschließlich '.hours($r['sum']['adjustment']).' Stunden Korrekturbuchungen. Zeiten in Stunden:Minuten.</p>';
}
/* Dependency-free PDF writer: WinAnsi text, vector tables and embedded company image. */
class SimplePDF {
 private array $streams=[];private string $s='';private ?array $logo=null;private int $page=0;
 public function __construct(){ $name=setting('company_logo');if($name&&is_file(storage_path($name))){$im=@imagecreatefromstring(file_get_contents(storage_path($name)));if($im){$w=imagesx($im);$h=imagesy($im);$bg=imagecreatetruecolor($w,$h);imagefill($bg,0,0,imagecolorallocate($bg,255,255,255));imagecopy($bg,$im,0,0,0,0,$w,$h);ob_start();imagejpeg($bg,null,85);$this->logo=['data'=>ob_get_clean(),'w'=>$w,'h'=>$h];imagedestroy($im);imagedestroy($bg);}} }
 public function page(string $title,string $subtitle): void {if($this->s!=='')$this->streams[]=$this->s;$this->s='';$this->page++;$this->text(36,38,setting('company'),16,true);$this->text(36,61,$title,12,true);$this->text(36,79,$subtitle,9);if($this->logo){$w=min(90,40*$this->logo['w']/$this->logo['h']);$h=$w*$this->logo['h']/$this->logo['w'];$this->s.="q $w 0 0 $h ".(559-$w).' '.(810-$h)." cm /Im1 Do Q\n";}$this->line(36,90,559,90);$this->text(36,813,'MaStunden · Erstellt '.local_time(now()).' · Seite '.$this->page,8);}
 public function text(float $x,float $y,string $text,int $size=9,bool $bold=false): void { $str=iconv('UTF-8','Windows-1252//TRANSLIT',$text);$str=str_replace(['\\','(',')',"\r","\n"],['\\\\','\\(','\\)',' ',' '],$str?:'');$this->s.='BT /'.($bold?'F2':'F1')." $size Tf 1 0 0 1 $x ".(842-$y)." Tm ($str) Tj ET\n"; }
 public function line(float $x,float $y,float $x2,float $y2): void {$this->s.="0.85 G 0.4 w $x ".(842-$y)." m $x2 ".(842-$y2)." l S 0 G\n";}
 public function output(): string {
  if($this->s!=='')$this->streams[]=$this->s;$objects=[1=>'',2=>'<< /Type /Catalog /Pages 1 0 R >>',3=>'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>',4=>'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>'];$kids=[];$n=5;$imageId=null;if($this->logo){$imageId=$n++;$data=$this->logo['data'];$objects[$imageId]='<< /Type /XObject /Subtype /Image /Width '.$this->logo['w'].' /Height '.$this->logo['h'].' /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length '.strlen($data).">>\nstream\n".$data."\nendstream";}
  foreach($this->streams as $stream){$page=$n++;$content=$n++;$kids[]="$page 0 R";$objects[$page]='<< /Type /Page /Parent 1 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R /F2 4 0 R >>'.($imageId?' /XObject << /Im1 '.$imageId.' 0 R >>':'').' >> /Contents '.$content.' 0 R >>';$objects[$content]='<< /Length '.strlen($stream).">>\nstream\n".$stream."endstream";}$objects[1]='<< /Type /Pages /Kids ['.implode(' ',$kids).'] /Count '.count($kids).' >>';ksort($objects);$pdf="%PDF-1.4\n%\xE2\xE3\xCF\xD3\n";$offsets=[0];foreach($objects as $id=>$value){$offsets[$id]=strlen($pdf);$pdf.="$id 0 obj\n$value\nendobj\n";}$xref=strlen($pdf);$pdf.="xref\n0 ".count($offsets)."\n0000000000 65535 f \n";for($i=1;$i<count($offsets);$i++)$pdf.=sprintf("%010d 00000 n \n",$offsets[$i]);return $pdf.'trailer << /Size '.count($offsets).' /Root 2 0 R >>' ."\nstartxref\n$xref\n%%EOF";
 }
}
function export_reports(string $format): never {
 $month=month_ok((string)($_GET['month']??substr(today(),0,7)));$ids=isset($_GET['users'])&&is_array($_GET['users'])?array_unique(array_map('intval',$_GET['users'])):[target()];if(count($ids)>250)fail('Maximal 250 Mitarbeiter pro Export.');foreach($ids as $id)owner($id);if(!$ids)fail('Mindestens einen Mitarbeiter auswählen.');$reports=[];foreach($ids as $id){if(!one('users','id=?',[$id]))fail('Mitarbeiter fehlt.');$reports[]=month_report($id,$month);}
 header('Cache-Control: no-store');
 if($format==='csv') {header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="MaStunden-'.$month.'.csv"');$out=fopen('php://output','w');fwrite($out,"\xEF\xBB\xBF");$write=function(array $row)use($out){$row=array_map(fn($v)=>is_string($v)&&preg_match('/^[=+@\-\t\r]/',$v)?"'".$v:$v,$row);fputcsv($out,$row,';','"','');};$write(['Mitarbeiter','Personalnummer','Datum','Arbeitsblöcke','Pause Minuten','Ist Minuten','Soll Minuten','Gutschrift Minuten','Saldo Minuten','Abwesenheit']);foreach($reports as $r){foreach($r['days'] as $d)$write([$r['user']['name'],$r['user']['personnel'],$d['day'],implode(', ',$d['blocks']),$d['break'],$d['work'],$d['target'],$d['credit'],$d['balance'],$d['label']]);$write([$r['user']['name'],$r['user']['personnel'],'Korrekturbuchungen','',0,0,0,0,$r['sum']['adjustment'],'']);}exit;}
 if($format==='print'){echo '<!doctype html><html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Monatszettel '.h($month).'</title><link rel="stylesheet" href="assets/app.css"><script src="assets/app.js" defer></script><body class="print"><button class="no-print" id="print-button">Drucken / als PDF speichern</button>';foreach($reports as $r){echo '<section class="print-page">'.logo().'<h1>'.h(setting('company')).'</h1><p>'.nl2br(h(setting('address'))).'</p><h2>Monatszettel '.$month.' · '.h($r['user']['name']).'</h2><p>Personalnummer: '.h($r['user']['personnel']).' · Status: '.badge(one('closures','user_id=? AND month=?',[$r['user']['id'],$month])['status']??'open').'</p>';report_table($r);echo '<p>Unterschrift Mitarbeiter: ____________________ &nbsp; Prüfung: ____________________</p><small>Erstellt '.h(local_time(now())).'</small></section>';}echo '</body></html>';exit;}
 if(!in_array($format,['pdf','summary'],true))fail('Unbekannter Export.');$pdf=new SimplePDF();
 if($format==='summary'){require_admin();$pdf->page('Teambericht · '.$month,'Stunden:Minuten · Korrekturen im Saldo enthalten');$y=115;foreach(['Mitarbeiter'=>36,'Ist'=>265,'Soll'=>325,'Gutschrift'=>385,'Saldo'=>465] as $label=>$x)$pdf->text($x,$y,$label,9,true);$y+=22;foreach($reports as $r){if($y>760){$pdf->page('Teambericht · '.$month,'Fortsetzung');$y=115;}$pdf->text(36,$y,mb_strimwidth($r['user']['name'],0,35,'…'),10);foreach(['work'=>265,'target'=>325,'credit'=>385,'balance'=>465] as $k=>$x)$pdf->text($x,$y,hours($r['sum'][$k]),10);$y+=23;}}
 else foreach($reports as $r){$c=one('closures','user_id=? AND month=?',[$r['user']['id'],$month]);$status=['open'=>'Offen','submitted'=>'Eingereicht','approved'=>'Freigegeben','returned'=>'Zurückgegeben'][$c['status']??'open'];$pdf->page('Monatszettel · '.$month,$r['user']['name'].' · Personalnr. '.$r['user']['personnel'].' · '.$status);$pdf->text(36,106,mb_strimwidth(str_replace(["\r","\n"],' ',setting('address')),0,100,'…'),8);$y=127;foreach(['Tag'=>36,'Arbeitsblöcke'=>84,'Pause'=>228,'Ist'=>272,'Soll'=>315,'Gutschr.'=>358,'Saldo'=>405,'Hinweis'=>452] as $label=>$x)$pdf->text($x,$y,$label,8,true);$y+=20;foreach($r['days'] as $d){$pdf->text(36,$y,substr($d['day'],8,2).'.'.substr($d['day'],5,2).'.',8);$blocks=implode(', ',$d['blocks']);$pdf->text(84,$y,mb_strimwidth($blocks,0,28,'…'),7);foreach(['break'=>228,'work'=>272,'target'=>315,'credit'=>358,'balance'=>405] as $k=>$x)$pdf->text($x,$y,hours($d[$k]),8);$pdf->text(452,$y,mb_strimwidth($d['label'],0,22,'…'),7);$pdf->line(36,$y+5,559,$y+5);$y+=17;}$y+=12;$pdf->text(36,$y,'Summe',10,true);foreach(['break'=>228,'work'=>272,'target'=>315,'credit'=>358,'balance'=>405] as $k=>$x)$pdf->text($x,$y,hours($r['sum'][$k]),9,true);$pdf->text(36,$y+22,'Saldo enthält '.hours($r['sum']['adjustment']).' Stunden Korrekturbuchungen.',8);$pdf->text(36,$y+62,'Unterschrift Mitarbeiter: __________________      Prüfung: __________________',9);
 // Detailed appendix avoids losing multiple blocks, pause intervals and cross-midnight offsets.
 $from=(new DateTimeImmutable($month.'-01',tz()))->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');$to=(new DateTimeImmutable($month.'-01',tz()))->modify('+1 month')->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');$entries=$r['entries']??rows('entries','user_id=? AND start_at<? AND (end_at IS NULL OR end_at>?)',[$r['user']['id'],$to,$from],'ORDER BY start_at');if($entries){$pdf->page('Einzelnachweis · '.$month,$r['user']['name'].' · lokale Zeiten mit UTC-Abstand');$y=115;foreach($entries as $e){$lines=['Arbeit: '.local_time($e['start_at'],'d.m. H:i P').' bis '.local_time($e['end_at'],'d.m. H:i P')];foreach(json_decode($e['breaks_json'],true) as $p)$lines[]='   Pause: '.local_time($p[0],'d.m. H:i P').' bis '.local_time($p[1],'d.m. H:i P');foreach($lines as $line){if($y>765){$pdf->page('Einzelnachweis · '.$month,$r['user']['name'].' · Fortsetzung');$y=115;}$pdf->text(36,$y,$line,9);$y+=16;}$y+=7;}}}
 header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="MaStunden-'.$month.'.pdf"');echo $pdf->output();exit;
}
