<?php
declare(strict_types=1);
if(PHP_VERSION_ID<80300){http_response_code(503);exit('MaStunden benötigt PHP 8.3 oder neuer. Bitte im Hostingpanel umstellen.');}
require_once __DIR__.'/lib/core.php';
require_once __DIR__.'/lib/install_storage.php';
require_once __DIR__.'/lib/install_ftp.php';
ini_set('display_errors','0');ini_set('session.use_strict_mode','1');session_name('MASTUNDEN_'.substr(hash('sha256',__DIR__),0,10));session_set_cookie_params(['lifetime'=>0,'path'=>rtrim(str_replace('\\','/',dirname($_SERVER['SCRIPT_NAME'])),'/').'/','secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','httponly'=>true,'samesite'=>'Lax']);session_start();header('X-Content-Type-Options: nosniff');header("Content-Security-Policy: default-src 'self'; style-src 'self'; form-action 'self'; frame-ancestors 'none'");
if(is_file(__DIR__.'/config.php')){http_response_code(403);exit('Installation gesperrt. MaStunden ist bereits eingerichtet.');}
$https=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off');$local=in_array($_SERVER['REMOTE_ADDR']??'',['127.0.0.1','::1'],true)||getenv('MASTUNDEN_LOCAL_TEST')==='1';
$ftpEnabled=post('ftp_enabled')==='1';
$checks=['PHP ab 8.3'=>version_compare(PHP_VERSION,'8.3','>='),'PDO MySQL'=>extension_loaded('pdo_mysql'),'ZIP'=>extension_loaded('zip'),'Fileinfo'=>extension_loaded('fileinfo'),'Mbstring'=>extension_loaded('mbstring'),'GD'=>extension_loaded('gd'),'OpenSSL'=>extension_loaded('openssl'),'HTTPS'=>$https||$local,'Programmordner beschreibbar oder FTP gewählt'=>is_writable(__DIR__)||$ftpEnabled];$error='';
$created=[];$createdStorage=null;$ftp=null;if($_SERVER['REQUEST_METHOD']==='POST')try{
 csrf_check();if(in_array(false,$checks,true))fail('Die Systemvoraussetzungen sind noch nicht erfüllt.');
 $prefix=post('prefix','ma_');if(!preg_match('/^[a-z][a-z0-9_]{0,24}$/D',$prefix))fail('Tabellenpräfix: Kleinbuchstaben, Zahlen und Unterstriche.');$port=(int)post('port','3306');if($port<1||$port>65535)fail('Ungültiger Datenbankport.');foreach(['host','database'] as $k)if(preg_match('/[;\r\n]/',post($k)))fail('Ungültige Datenbankangabe.');$email=strtolower(post('email'));if(!filter_var($email,FILTER_VALIDATE_EMAIL))fail('Ungültige E-Mail-Adresse.');password_rule(post('password'));if(post('password')!==post('repeat'))fail('Passwörter stimmen nicht überein.');$company=bounded(post('company'),190);if($company==='')fail('Unternehmensname fehlt.');if(post('name')==='')fail('Ihr Name fehlt.');
 $GLOBALS['config']=['host'=>post('host'),'port'=>$port,'database'=>post('database'),'username'=>post('username'),'password'=>post('db_password'),'prefix'=>$prefix,'storage'=>'','key'=>bin2hex(random_bytes(32))];
 $lock=fopen(sys_get_temp_dir().'/mastunden-install-'.hash('sha256',__DIR__).'.lock','c');if(!$lock||!flock($lock,LOCK_EX|LOCK_NB))fail('Eine Installation läuft bereits.');if(is_file(__DIR__.'/config.php'))fail('Installation bereits abgeschlossen.');
 $serverVersion=(string)db()->getAttribute(PDO::ATTR_SERVER_VERSION);if(stripos($serverVersion,'MariaDB')!==false||version_compare($serverVersion,'8.0','<'))fail('Diese Version benötigt MySQL 8.0 oder neuer. MariaDB ist in dieser Ausgabe nicht freigegeben.');foreach(schema() as $name=>$definition){$exists=q('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?',[$prefix.$name])->fetchColumn();if($exists)fail('Tabellen mit diesem Präfix existieren bereits. Anderes Präfix wählen.');}
 if($ftpEnabled)$ftp=new InstallerFtp(__DIR__,(string)($_SERVER['DOCUMENT_ROOT']??''),['host'=>post('ftp_host'),'port'=>(int)post('ftp_port','21'),'username'=>post('ftp_user'),'password'=>(string)($_POST['ftp_password']??''),'path'=>post('ftp_path'),'protocol'=>post('ftp_protocol','ftps')]);
 try{$createdStorage=$ftp?$ftp->createStorage():create_private_storage((string)($_SERVER['DOCUMENT_ROOT']??''));}catch(RuntimeException $storageError){$createdStorage=create_verified_web_storage(__DIR__);}$GLOBALS['config']['storage']=$createdStorage;
 foreach(schema() as $name=>$definition){q('CREATE TABLE '.table($name).' ('.$definition.') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');$created[]=$name;}
 $id=insert('users',['email'=>$email,'name'=>bounded(post('name'),190),'password'=>password_hash(post('password'),PASSWORD_DEFAULT),'role'=>'admin','vacation_days'=>0,'employment_start'=>gmdate('Y-m-d'),'created_at'=>now()]);
 foreach(['company'=>$company,'timezone'=>'Europe/Berlin','color'=>'#117a82','upload_mb'=>'10','schema_version'=>'1','max_daily'=>'600','pause_short'=>'30','pause_long'=>'45','rest_hours'=>'11','retention_days'=>'0','installed_at'=>now(),'session_epoch'=>bin2hex(random_bytes(16))] as $k=>$v)set_setting($k,$v);
 $recovery=bin2hex(random_bytes(24));set_setting('recovery_hash',password_hash($recovery,PASSWORD_DEFAULT));$conf="<?php\n// MaStunden: do not overwrite during updates.\nreturn ".var_export(cfg(),true).";\n";if($ftp){$ftp->writeConfig($conf);}else{$temporary=__DIR__.'/config-new.php';if(file_put_contents($temporary,$conf,LOCK_EX)!==strlen($conf)){@unlink($temporary);fail('Konfiguration konnte nicht geschrieben werden.');}@chmod($temporary,0600);if(!rename($temporary,__DIR__.'/config.php')){@unlink($temporary);fail('Konfiguration konnte nicht fertiggestellt werden.');}}session_regenerate_id(true);$_SESSION['uid']=$id;$_SESSION['password_sig']=hash('sha256',one('users','id=?',[$id])['password']);$_SESSION['epoch']=setting('session_epoch');$_SESSION['last_activity']=time();$_SESSION['recovery_once']=$recovery;go('index.php?page=welcome');
}catch(Throwable $e){if(!is_file(__DIR__.'/config.php')){foreach($created as $t){try{q('DROP TABLE '.table($t));}catch(Throwable $ignored){}}if($createdStorage!==null){if(isset($GLOBALS['config']['storage_guard_sha256']))@unlink($createdStorage.'/.htaccess');@rmdir($createdStorage);}if($ftp)$ftp->cleanup();}$error=$e instanceof PDOException?'Datenbankverbindung oder Tabellenanlage fehlgeschlagen. Angaben, Berechtigungen und Präfix prüfen.':$e->getMessage();}
?>
<!doctype html><html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>MaStunden installieren</title><link rel="stylesheet" href="assets/app.css?v=<?=h(APP_VERSION)?>"><body class="setup"><main class="setup-card"><div class="brand-mark">Ma<span>St</span></div><div class="developer-credit"><span>Entwickelt von</span><img src="assets/it-janz-logo.png" alt="IT-Janz" width="300" height="107"></div><h1>Willkommen bei MaStunden.</h1><p class="muted">In wenigen Schritten zur eigenen Zeiterfassung.</p><div class="checks"><?php foreach($checks as $k=>$v)echo '<span class="badge '.($v?'approved':'rejected').'">'.($v?'✓ ':'✕ ').h($k).'</span>';?></div><?php if($error)echo '<div class="alert error">'.h($error).'</div>';?><form method="post"><?=csrf_field()?>
<h2>1 · Datenbank des Hostinganbieters</h2><div class="form-grid"><label>Server<input name="host" value="<?=h(post('host','localhost'))?>" required></label><label>Port<input name="port" type="number" value="<?=h(post('port','3306'))?>" required></label><label>Datenbankname<input name="database" value="<?=h(post('database'))?>" required></label><label>Datenbankbenutzer<input name="username" value="<?=h(post('username'))?>" required></label><label>Datenbankpasswort<input name="db_password" type="password" required></label><label>Tabellenpräfix<input name="prefix" value="<?=h(post('prefix','ma_'))?>" required></label></div>
<p class="muted">MaStunden legt den geschützten Speicher während der Installation automatisch an.</p>
<details<?= $ftpEnabled?' open':'' ?>><summary>Optional: Dateien mit FTP / FTPS einrichten</summary><p class="muted">Wenn PHP keine Ordner oder Programmdateien anlegen darf, kann MaStunden dafür Ihren FTP-Zugang verwenden. Die Zugangsdaten werden nicht gespeichert. Der FTP-Zugang muss auch den Ordner oberhalb des öffentlichen Webverzeichnisses erreichen. PHP muss den angelegten Speicher anschließend lesen und beschreiben können.</p><label class="checkbox"><input type="checkbox" name="ftp_enabled" value="1"<?= $ftpEnabled?' checked':'' ?>> FTP-Einrichtung verwenden</label><div class="form-grid"><label>Verbindung<select name="ftp_protocol"><option value="ftps">FTPS (verschlüsselt, empfohlen)</option><option value="ftp"<?=post('ftp_protocol')==='ftp'?' selected':''?>>FTP (unverschlüsselt)</option></select></label><label>FTP-Server<input name="ftp_host" value="<?=h(post('ftp_host'))?>" autocomplete="off"></label><label>Port<input type="number" name="ftp_port" value="<?=h(post('ftp_port','21'))?>" min="1" max="65535"></label><label>FTP-Benutzer<input name="ftp_user" value="<?=h(post('ftp_user'))?>" autocomplete="off"></label><label>FTP-Passwort<input type="password" name="ftp_password" autocomplete="new-password"></label><label>FTP-Ordner von MaStunden<input name="ftp_path" value="<?=h(post('ftp_path'))?>" placeholder="/public_html/mastunden"></label></div><p class="muted">Gemeint ist der Ordner, in dem install.php liegt, so wie er im FTP-Programm angezeigt wird. FTPS verwendet eine geprüfte TLS-Verbindung; SFTP wird nicht unterstützt.</p></details>
<h2>2 · Unternehmen und Administrator</h2><div class="form-grid"><label>Unternehmen<input name="company" value="<?=h(post('company'))?>" required></label><label>Ihr Name<input name="name" value="<?=h(post('name'))?>" required></label><label class="full-width">E-Mail für die Anmeldung<input name="email" type="email" value="<?=h(post('email'))?>" required></label><label>Passwort (12–72 Zeichen)<input name="password" type="password" minlength="12" maxlength="72" required></label><label>Passwort wiederholen<input name="repeat" type="password" required></label></div><button>MaStunden installieren</button></form></main></body></html>
